apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.tenant }}-vault
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: {{ .Values.vault.mountPoint }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMountPath }}
          role: {{ .Values.vault.esoRole }}
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
