apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: it-spark-pi-{{ params.suffix }}-{{ run_id | replace(':', '-') | replace('+', '-') | replace('.', '-') | replace('_', '-') | lower }}
  namespace: {{ params.namespace }}
spec:
  type: Scala
  mode: cluster
  image: apache/spark:4.0.4
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.13-4.0.4.jar
  sparkVersion: "4.0.4"
  restartPolicy:
    type: Never
  driver:
    serviceAccount: {{ params.service_account }}
    cores: 1
    memory: 512m
  executor:
    instances: 1
    cores: 1
    memory: 512m
